steps:
  # Build the server image from the Dockerfile in the 'drive-server' directory
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'drive-server' # This should be the path to the directory containing your Dockerfile
    args: ['build', '-t', 'gcr.io/eminent-bond-404002/drive-server:$SHORT_SHA', '.']

  # Push the server image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/eminent-bond-404002/drive-server:$SHORT_SHA']

  # Deploy the server image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'drive-server-service', '--image', 'gcr.io/eminent-bond-404002/drive-server:$SHORT_SHA', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/eminent-bond-404002/drive-server:$SHORT_SHA'

# Set timeout to "1600s" if you expect builds to take longer.
timeout: "1600s"
