steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/eminent-bond-404002/drive-server:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'drive-service', '--image', 'gcr.io/eminent-bond-404002/drive-server:$SHORT_SHA', '--platform', 'managed', '--region', 'us-central1']
