steps:
  # Install npm dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: 'npm_install'

  # Debug: List googleapis directory contents
  - name: 'ubuntu'
    args: ['ls', '-la', 'node_modules/googleapis']
    id: 'list_googleapis'

  # Continue with other steps...
